name: basic-check

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - '**'

jobs:

  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: install deps
        run: sudo apt-get install make ftp git bzr curl wget -y && sudo apt upgrade -y

      - name: dep
        env:
          GOPROXY: "https://proxy.golang.org,direct"
          GO111MODULE: "on"
        run: |
          make deps

      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.44.2
          golangci-lint run --timeout 10m

      - name: Unit Test
        run: go test -integration=false -unit=true -v ./...

      - name: Integration Test
        run: go test -integration=true -unit=false -v ./...

      - name: Compatible all
        run: |
          make compatible-all

      - name: Gen all
        run: |
          make gen-all

      - name: Detect changes
        run: |
          git status --porcelain
          test -z "$(git status --porcelain)"

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org,direct"
          GO111MODULE: "on"
        run: |
          make

      - name: Run coverage
        run:  go test -coverpkg=./... -race -coverprofile=coverage.txt -covermode=atomic ./... -integration=true -unit=true

      - name: Upload
        uses: codecov/codecov-action@v2
        with:
          token:
          files: ./coverage.txt
          flags: unittests
          name: venus-market
          fail_ci_if_error: true
          verbose: true